# The Docker Config version. Do not change.
version: "3.1"
services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PW}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - movie_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volume:
  movie_data: